### ISSUE TITLE
Problem in Responsive View

### ISSUE THREAD

**Issue by AliBahaari** [umeshmk/Tailwindcss-cheatsheet#1]
Hi there!
Thanks for the cheat sheet.
I checked the site out and I had a little problem with responsive view on my screen size which is 1366 x 768.
I took a screenshot it may help you to understand what I say.
Good luck!

![IMG](https://user-images.githubusercontent.com/8419324/136460330-efca2639-5c00-4bd7-a092-b14916788ae8.png)

**Comment by umeshmk** [comment]
Thanks for your interest. 
This issue has been fixed in new release (v2.1). Do check out.

**Comment by AliBahaari** [comment]
Let me be honest,
It's wonderful!
Thanks
